name: Linux

on: 
  push:
    paths:
      - '.github/**'
      - 'sp/src/**'
  pull_request:
   paths:
      - 'sp/src/**'

env:
  STEAM_RUNTIME_PATH: /valve/steam-runtime
  CCACHE_VERSION: 4.2.1
  CCACHE_DIR: ${{ github.workspace }}/sp/src/ccache

jobs:
  build:
    runs-on:
      ubuntu-20.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
      
      
      - name: Configure dependencies
        run: sudo apt update && sudo apt install -y build-essential gcc-multilib g++-multilib

      - name: Create project
        run: cd sp/src && sudo devtools/bin/vpc /sdk2013ce /2013 +game /mksln sdk2013ce
      
      - name: Download Steam runtime
        run: |
          cd /
          sudo mkdir valve
          cd valve
          sudo wget http://media.steampowered.com/client/runtime/steam-runtime-sdk_latest.tar.xz
          sudo tar xvf steam-runtime-sdk_latest.tar.xz
          sudo mv steam-runtime-sdk_2013-09-05 steam-runtime
          sudo bash $STEAM_RUNTIME_PATH/setup.sh --release --target="i386 amd64" --auto-upgrade

      - name: Build project
        run: cd sp/src && sudo make -f sdk2013ce.mak
      
      - name: Pack
        run: |
          sudo tar cJfv Linux.tar.xz game/mod_sdk2013ce/bin


      - name: Upload product
        uses: actions/upload-artifact@v2
        with:
          name: linux_sp_sdk2013ce
          path: Linux.tar.xz
